/*
 * This file is generated by jOOQ.
 */
package com.mycompany.myapp.database.tables.pojos;

import java.io.Serializable;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JhiAuthority implements Serializable {

    private static final long serialVersionUID = 1L;

    private String name;

    public JhiAuthority() {}

    public JhiAuthority(JhiAuthority value) {
        this.name = value.name;
    }

    public JhiAuthority(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>jhi_authority.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>jhi_authority.name</code>.
     */
    public JhiAuthority setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        final JhiAuthority other = (JhiAuthority) obj;
        if (this.name == null) {
            if (other.name != null) return false;
        } else if (!this.name.equals(other.name)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JhiAuthority (");

        sb.append(name);

        sb.append(")");
        return sb.toString();
    }
}
