/*
 * This file is generated by jOOQ.
 */
package com.mycompany.myapp.database.tables.pojos;

import java.io.Serializable;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JhiUserAuthority implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long userId;
    private String authorityName;

    public JhiUserAuthority() {}

    public JhiUserAuthority(JhiUserAuthority value) {
        this.userId = value.userId;
        this.authorityName = value.authorityName;
    }

    public JhiUserAuthority(Long userId, String authorityName) {
        this.userId = userId;
        this.authorityName = authorityName;
    }

    /**
     * Getter for <code>jhi_user_authority.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>jhi_user_authority.user_id</code>.
     */
    public JhiUserAuthority setUserId(Long userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>jhi_user_authority.authority_name</code>.
     */
    public String getAuthorityName() {
        return this.authorityName;
    }

    /**
     * Setter for <code>jhi_user_authority.authority_name</code>.
     */
    public JhiUserAuthority setAuthorityName(String authorityName) {
        this.authorityName = authorityName;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        final JhiUserAuthority other = (JhiUserAuthority) obj;
        if (this.userId == null) {
            if (other.userId != null) return false;
        } else if (!this.userId.equals(other.userId)) return false;
        if (this.authorityName == null) {
            if (other.authorityName != null) return false;
        } else if (!this.authorityName.equals(other.authorityName)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.authorityName == null) ? 0 : this.authorityName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JhiUserAuthority (");

        sb.append(userId);
        sb.append(", ").append(authorityName);

        sb.append(")");
        return sb.toString();
    }
}
