/*
 * This file is generated by jOOQ.
 */
package com.mycompany.myapp.database.tables.pojos;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JhiUser implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String login;
    private String passwordHash;
    private String firstName;
    private String lastName;
    private String email;
    private String imageUrl;
    private Byte activated;
    private String langKey;
    private String activationKey;
    private String resetKey;
    private String createdBy;
    private LocalDateTime createdDate;
    private LocalDateTime resetDate;
    private String lastModifiedBy;
    private LocalDateTime lastModifiedDate;

    public JhiUser() {}

    public JhiUser(JhiUser value) {
        this.id = value.id;
        this.login = value.login;
        this.passwordHash = value.passwordHash;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.email = value.email;
        this.imageUrl = value.imageUrl;
        this.activated = value.activated;
        this.langKey = value.langKey;
        this.activationKey = value.activationKey;
        this.resetKey = value.resetKey;
        this.createdBy = value.createdBy;
        this.createdDate = value.createdDate;
        this.resetDate = value.resetDate;
        this.lastModifiedBy = value.lastModifiedBy;
        this.lastModifiedDate = value.lastModifiedDate;
    }

    public JhiUser(
        Long id,
        String login,
        String passwordHash,
        String firstName,
        String lastName,
        String email,
        String imageUrl,
        Byte activated,
        String langKey,
        String activationKey,
        String resetKey,
        String createdBy,
        LocalDateTime createdDate,
        LocalDateTime resetDate,
        String lastModifiedBy,
        LocalDateTime lastModifiedDate
    ) {
        this.id = id;
        this.login = login;
        this.passwordHash = passwordHash;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.imageUrl = imageUrl;
        this.activated = activated;
        this.langKey = langKey;
        this.activationKey = activationKey;
        this.resetKey = resetKey;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.resetDate = resetDate;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * Getter for <code>jhi_user.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>jhi_user.id</code>.
     */
    public JhiUser setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>jhi_user.login</code>.
     */
    public String getLogin() {
        return this.login;
    }

    /**
     * Setter for <code>jhi_user.login</code>.
     */
    public JhiUser setLogin(String login) {
        this.login = login;
        return this;
    }

    /**
     * Getter for <code>jhi_user.password_hash</code>.
     */
    public String getPasswordHash() {
        return this.passwordHash;
    }

    /**
     * Setter for <code>jhi_user.password_hash</code>.
     */
    public JhiUser setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
        return this;
    }

    /**
     * Getter for <code>jhi_user.first_name</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>jhi_user.first_name</code>.
     */
    public JhiUser setFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * Getter for <code>jhi_user.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>jhi_user.last_name</code>.
     */
    public JhiUser setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    /**
     * Getter for <code>jhi_user.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>jhi_user.email</code>.
     */
    public JhiUser setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>jhi_user.image_url</code>.
     */
    public String getImageUrl() {
        return this.imageUrl;
    }

    /**
     * Setter for <code>jhi_user.image_url</code>.
     */
    public JhiUser setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
        return this;
    }

    /**
     * Getter for <code>jhi_user.activated</code>.
     */
    public Byte getActivated() {
        return this.activated;
    }

    /**
     * Setter for <code>jhi_user.activated</code>.
     */
    public JhiUser setActivated(Byte activated) {
        this.activated = activated;
        return this;
    }

    /**
     * Getter for <code>jhi_user.lang_key</code>.
     */
    public String getLangKey() {
        return this.langKey;
    }

    /**
     * Setter for <code>jhi_user.lang_key</code>.
     */
    public JhiUser setLangKey(String langKey) {
        this.langKey = langKey;
        return this;
    }

    /**
     * Getter for <code>jhi_user.activation_key</code>.
     */
    public String getActivationKey() {
        return this.activationKey;
    }

    /**
     * Setter for <code>jhi_user.activation_key</code>.
     */
    public JhiUser setActivationKey(String activationKey) {
        this.activationKey = activationKey;
        return this;
    }

    /**
     * Getter for <code>jhi_user.reset_key</code>.
     */
    public String getResetKey() {
        return this.resetKey;
    }

    /**
     * Setter for <code>jhi_user.reset_key</code>.
     */
    public JhiUser setResetKey(String resetKey) {
        this.resetKey = resetKey;
        return this;
    }

    /**
     * Getter for <code>jhi_user.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>jhi_user.created_by</code>.
     */
    public JhiUser setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>jhi_user.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>jhi_user.created_date</code>.
     */
    public JhiUser setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Getter for <code>jhi_user.reset_date</code>.
     */
    public LocalDateTime getResetDate() {
        return this.resetDate;
    }

    /**
     * Setter for <code>jhi_user.reset_date</code>.
     */
    public JhiUser setResetDate(LocalDateTime resetDate) {
        this.resetDate = resetDate;
        return this;
    }

    /**
     * Getter for <code>jhi_user.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    /**
     * Setter for <code>jhi_user.last_modified_by</code>.
     */
    public JhiUser setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
        return this;
    }

    /**
     * Getter for <code>jhi_user.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    /**
     * Setter for <code>jhi_user.last_modified_date</code>.
     */
    public JhiUser setLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        final JhiUser other = (JhiUser) obj;
        if (this.id == null) {
            if (other.id != null) return false;
        } else if (!this.id.equals(other.id)) return false;
        if (this.login == null) {
            if (other.login != null) return false;
        } else if (!this.login.equals(other.login)) return false;
        if (this.passwordHash == null) {
            if (other.passwordHash != null) return false;
        } else if (!this.passwordHash.equals(other.passwordHash)) return false;
        if (this.firstName == null) {
            if (other.firstName != null) return false;
        } else if (!this.firstName.equals(other.firstName)) return false;
        if (this.lastName == null) {
            if (other.lastName != null) return false;
        } else if (!this.lastName.equals(other.lastName)) return false;
        if (this.email == null) {
            if (other.email != null) return false;
        } else if (!this.email.equals(other.email)) return false;
        if (this.imageUrl == null) {
            if (other.imageUrl != null) return false;
        } else if (!this.imageUrl.equals(other.imageUrl)) return false;
        if (this.activated == null) {
            if (other.activated != null) return false;
        } else if (!this.activated.equals(other.activated)) return false;
        if (this.langKey == null) {
            if (other.langKey != null) return false;
        } else if (!this.langKey.equals(other.langKey)) return false;
        if (this.activationKey == null) {
            if (other.activationKey != null) return false;
        } else if (!this.activationKey.equals(other.activationKey)) return false;
        if (this.resetKey == null) {
            if (other.resetKey != null) return false;
        } else if (!this.resetKey.equals(other.resetKey)) return false;
        if (this.createdBy == null) {
            if (other.createdBy != null) return false;
        } else if (!this.createdBy.equals(other.createdBy)) return false;
        if (this.createdDate == null) {
            if (other.createdDate != null) return false;
        } else if (!this.createdDate.equals(other.createdDate)) return false;
        if (this.resetDate == null) {
            if (other.resetDate != null) return false;
        } else if (!this.resetDate.equals(other.resetDate)) return false;
        if (this.lastModifiedBy == null) {
            if (other.lastModifiedBy != null) return false;
        } else if (!this.lastModifiedBy.equals(other.lastModifiedBy)) return false;
        if (this.lastModifiedDate == null) {
            if (other.lastModifiedDate != null) return false;
        } else if (!this.lastModifiedDate.equals(other.lastModifiedDate)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.login == null) ? 0 : this.login.hashCode());
        result = prime * result + ((this.passwordHash == null) ? 0 : this.passwordHash.hashCode());
        result = prime * result + ((this.firstName == null) ? 0 : this.firstName.hashCode());
        result = prime * result + ((this.lastName == null) ? 0 : this.lastName.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.imageUrl == null) ? 0 : this.imageUrl.hashCode());
        result = prime * result + ((this.activated == null) ? 0 : this.activated.hashCode());
        result = prime * result + ((this.langKey == null) ? 0 : this.langKey.hashCode());
        result = prime * result + ((this.activationKey == null) ? 0 : this.activationKey.hashCode());
        result = prime * result + ((this.resetKey == null) ? 0 : this.resetKey.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.createdDate == null) ? 0 : this.createdDate.hashCode());
        result = prime * result + ((this.resetDate == null) ? 0 : this.resetDate.hashCode());
        result = prime * result + ((this.lastModifiedBy == null) ? 0 : this.lastModifiedBy.hashCode());
        result = prime * result + ((this.lastModifiedDate == null) ? 0 : this.lastModifiedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JhiUser (");

        sb.append(id);
        sb.append(", ").append(login);
        sb.append(", ").append(passwordHash);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(email);
        sb.append(", ").append(imageUrl);
        sb.append(", ").append(activated);
        sb.append(", ").append(langKey);
        sb.append(", ").append(activationKey);
        sb.append(", ").append(resetKey);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(resetDate);
        sb.append(", ").append(lastModifiedBy);
        sb.append(", ").append(lastModifiedDate);

        sb.append(")");
        return sb.toString();
    }
}
