/*
 * This file is generated by jOOQ.
 */
package com.mycompany.myapp.database.tables.records;

import com.mycompany.myapp.database.tables.JhiAuthority;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JhiAuthorityRecord extends UpdatableRecordImpl<JhiAuthorityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>jhi_authority.name</code>.
     */
    public JhiAuthorityRecord setName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>jhi_authority.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JhiAuthorityRecord
     */
    public JhiAuthorityRecord() {
        super(JhiAuthority.JHI_AUTHORITY);
    }

    /**
     * Create a detached, initialised JhiAuthorityRecord
     */
    public JhiAuthorityRecord(String name) {
        super(JhiAuthority.JHI_AUTHORITY);
        setName(name);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised JhiAuthorityRecord
     */
    public JhiAuthorityRecord(com.mycompany.myapp.database.tables.pojos.JhiAuthority value) {
        super(JhiAuthority.JHI_AUTHORITY);
        if (value != null) {
            setName(value.getName());
            resetChangedOnNotNull();
        }
    }
}
