/*
 * This file is generated by jOOQ.
 */
package com.mycompany.myapp.database.tables.records;

import com.mycompany.myapp.database.tables.JhiUser;
import java.time.LocalDateTime;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JhiUserRecord extends UpdatableRecordImpl<JhiUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>jhi_user.id</code>.
     */
    public JhiUserRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>jhi_user.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>jhi_user.login</code>.
     */
    public JhiUserRecord setLogin(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>jhi_user.login</code>.
     */
    public String getLogin() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jhi_user.password_hash</code>.
     */
    public JhiUserRecord setPasswordHash(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>jhi_user.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jhi_user.first_name</code>.
     */
    public JhiUserRecord setFirstName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>jhi_user.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>jhi_user.last_name</code>.
     */
    public JhiUserRecord setLastName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>jhi_user.last_name</code>.
     */
    public String getLastName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>jhi_user.email</code>.
     */
    public JhiUserRecord setEmail(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>jhi_user.email</code>.
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>jhi_user.image_url</code>.
     */
    public JhiUserRecord setImageUrl(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>jhi_user.image_url</code>.
     */
    public String getImageUrl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>jhi_user.activated</code>.
     */
    public JhiUserRecord setActivated(Byte value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>jhi_user.activated</code>.
     */
    public Byte getActivated() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>jhi_user.lang_key</code>.
     */
    public JhiUserRecord setLangKey(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>jhi_user.lang_key</code>.
     */
    public String getLangKey() {
        return (String) get(8);
    }

    /**
     * Setter for <code>jhi_user.activation_key</code>.
     */
    public JhiUserRecord setActivationKey(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>jhi_user.activation_key</code>.
     */
    public String getActivationKey() {
        return (String) get(9);
    }

    /**
     * Setter for <code>jhi_user.reset_key</code>.
     */
    public JhiUserRecord setResetKey(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>jhi_user.reset_key</code>.
     */
    public String getResetKey() {
        return (String) get(10);
    }

    /**
     * Setter for <code>jhi_user.created_by</code>.
     */
    public JhiUserRecord setCreatedBy(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>jhi_user.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(11);
    }

    /**
     * Setter for <code>jhi_user.created_date</code>.
     */
    public JhiUserRecord setCreatedDate(LocalDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>jhi_user.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>jhi_user.reset_date</code>.
     */
    public JhiUserRecord setResetDate(LocalDateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>jhi_user.reset_date</code>.
     */
    public LocalDateTime getResetDate() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>jhi_user.last_modified_by</code>.
     */
    public JhiUserRecord setLastModifiedBy(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>jhi_user.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(14);
    }

    /**
     * Setter for <code>jhi_user.last_modified_date</code>.
     */
    public JhiUserRecord setLastModifiedDate(LocalDateTime value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>jhi_user.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JhiUserRecord
     */
    public JhiUserRecord() {
        super(JhiUser.JHI_USER);
    }

    /**
     * Create a detached, initialised JhiUserRecord
     */
    public JhiUserRecord(
        Long id,
        String login,
        String passwordHash,
        String firstName,
        String lastName,
        String email,
        String imageUrl,
        Byte activated,
        String langKey,
        String activationKey,
        String resetKey,
        String createdBy,
        LocalDateTime createdDate,
        LocalDateTime resetDate,
        String lastModifiedBy,
        LocalDateTime lastModifiedDate
    ) {
        super(JhiUser.JHI_USER);
        setId(id);
        setLogin(login);
        setPasswordHash(passwordHash);
        setFirstName(firstName);
        setLastName(lastName);
        setEmail(email);
        setImageUrl(imageUrl);
        setActivated(activated);
        setLangKey(langKey);
        setActivationKey(activationKey);
        setResetKey(resetKey);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setResetDate(resetDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised JhiUserRecord
     */
    public JhiUserRecord(com.mycompany.myapp.database.tables.pojos.JhiUser value) {
        super(JhiUser.JHI_USER);
        if (value != null) {
            setId(value.getId());
            setLogin(value.getLogin());
            setPasswordHash(value.getPasswordHash());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            setEmail(value.getEmail());
            setImageUrl(value.getImageUrl());
            setActivated(value.getActivated());
            setLangKey(value.getLangKey());
            setActivationKey(value.getActivationKey());
            setResetKey(value.getResetKey());
            setCreatedBy(value.getCreatedBy());
            setCreatedDate(value.getCreatedDate());
            setResetDate(value.getResetDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setLastModifiedDate(value.getLastModifiedDate());
            resetChangedOnNotNull();
        }
    }
}
