/*
 * This file is generated by jOOQ.
 */
package com.mycompany.myapp.database.tables.daos;

import com.mycompany.myapp.database.tables.JhiUserAuthority;
import com.mycompany.myapp.database.tables.records.JhiUserAuthorityRecord;
import java.util.List;
import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JhiUserAuthorityDao
    extends DAOImpl<JhiUserAuthorityRecord, com.mycompany.myapp.database.tables.pojos.JhiUserAuthority, Record2<Long, String>> {

    /**
     * Create a new JhiUserAuthorityDao without any configuration
     */
    public JhiUserAuthorityDao() {
        super(JhiUserAuthority.JHI_USER_AUTHORITY, com.mycompany.myapp.database.tables.pojos.JhiUserAuthority.class);
    }

    /**
     * Create a new JhiUserAuthorityDao with an attached configuration
     */
    public JhiUserAuthorityDao(Configuration configuration) {
        super(JhiUserAuthority.JHI_USER_AUTHORITY, com.mycompany.myapp.database.tables.pojos.JhiUserAuthority.class, configuration);
    }

    @Override
    public Record2<Long, String> getId(com.mycompany.myapp.database.tables.pojos.JhiUserAuthority object) {
        return compositeKeyRecord(object.getUserId(), object.getAuthorityName());
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mycompany.myapp.database.tables.pojos.JhiUserAuthority> fetchRangeOfUserId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(JhiUserAuthority.JHI_USER_AUTHORITY.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.mycompany.myapp.database.tables.pojos.JhiUserAuthority> fetchByUserId(Long... values) {
        return fetch(JhiUserAuthority.JHI_USER_AUTHORITY.USER_ID, values);
    }

    /**
     * Fetch records that have <code>authority_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mycompany.myapp.database.tables.pojos.JhiUserAuthority> fetchRangeOfAuthorityName(
        String lowerInclusive,
        String upperInclusive
    ) {
        return fetchRange(JhiUserAuthority.JHI_USER_AUTHORITY.AUTHORITY_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>authority_name IN (values)</code>
     */
    public List<com.mycompany.myapp.database.tables.pojos.JhiUserAuthority> fetchByAuthorityName(String... values) {
        return fetch(JhiUserAuthority.JHI_USER_AUTHORITY.AUTHORITY_NAME, values);
    }
}
