/*
 * This file is generated by jOOQ.
 */
package com.mycompany.myapp.database;

import com.mycompany.myapp.database.tables.Databasechangelog;
import com.mycompany.myapp.database.tables.Databasechangeloglock;
import com.mycompany.myapp.database.tables.JhiAuthority;
import com.mycompany.myapp.database.tables.JhiUser;
import com.mycompany.myapp.database.tables.JhiUserAuthority;
import java.util.Arrays;
import java.util.List;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>jhi_authority</code>.
     */
    public final JhiAuthority JHI_AUTHORITY = JhiAuthority.JHI_AUTHORITY;

    /**
     * The table <code>jhi_user</code>.
     */
    public final JhiUser JHI_USER = JhiUser.JHI_USER;

    /**
     * The table <code>jhi_user_authority</code>.
     */
    public final JhiUserAuthority JHI_USER_AUTHORITY = JhiUserAuthority.JHI_USER_AUTHORITY;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }

    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            JhiAuthority.JHI_AUTHORITY,
            JhiUser.JHI_USER,
            JhiUserAuthority.JHI_USER_AUTHORITY
        );
    }
}
