/*
 * This file is generated by jOOQ.
 */
package com.mycompany.myapp.database;

import com.mycompany.myapp.database.tables.Databasechangelog;
import com.mycompany.myapp.database.tables.Databasechangeloglock;
import com.mycompany.myapp.database.tables.JhiAuthority;
import com.mycompany.myapp.database.tables.JhiUser;
import com.mycompany.myapp.database.tables.JhiUserAuthority;

/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>jhi_authority</code>.
     */
    public static final JhiAuthority JHI_AUTHORITY = JhiAuthority.JHI_AUTHORITY;

    /**
     * The table <code>jhi_user</code>.
     */
    public static final JhiUser JHI_USER = JhiUser.JHI_USER;

    /**
     * The table <code>jhi_user_authority</code>.
     */
    public static final JhiUserAuthority JHI_USER_AUTHORITY = JhiUserAuthority.JHI_USER_AUTHORITY;
}
